### ISSUE TITLE
CRUD Operations on schedules (Back End)

### ISSUE THREAD

**Issue by seanaocostello** [ucsb-cs156-f20/proj-ucsb-courses-search#35]
# User Story

As a student I can create and edit named schedules so that I can plan my classes.

# Acceptance Criteria

- [x] There is a way to store schedules in a database
- [x] I should be able to create new schedules and set their names.
- [x] There is a way to delete entire schedules
- [x] There is a way to modify schedule names

# Implementation Todos

Back end:

- [x] Getter and setter methods for the Schedule object.
- [x] Create a function to load a schedule object from the database
- [x] Create a function that allows us to persist a schedule object to the database
- [x] Create a function that allows deletion of a schedule from the database

...

Testing:

- [x] Test that a schedule can be created
- [x] Test that a schedule loads to the database correctly
- [x] Test basic schedule functionality (change names/ change description/ change quarter)
- [x] Test that these changes persist after the schedule is pushed to the database and reloaded.
- [x] Test that the schedule can be deleted
- [x] Test that the schedule can be deleted from the database
...

**Comment by Mitchell57** [comment]
Added ScheduleItem entity, follows format of Course document, except:

- all variables are strings / numbers
- there is only one course section
