### ISSUE TITLE
Average class size by department

### ISSUE THREAD

**Issue by hdinh77** [ucsb-cs156-f20/proj-ucsb-courses-search#46]
# User Story

As a user I can find the average class size(not occupancy) within a specified start and end quarter so that we can view the statistics across multiple departments(Including Undergraduate and Graduate Courses).

# Acceptance Criteria

- [x] In the Statistics dropdown menu, there should be an entry that links to a page that allows you to see the average class size by department.
- [x] There is a form on the average class size page that lets you select a quarter range.
- [x] After submitting the form, it should display average class sizes across all departments.
...

# Implementation Todos

Front end:

- [x] Create a ClassSize.js page that is linked in the Statistics Navbar
- [x] Add a form that allows the user to select a quarter range
- [x] After selecting the quarter range, the results appear in a neatly formed table 
...

Back end:

- [x] Endpoint to retrieve occupancy information given a department, start and end quarters
...

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage
...

**Comment by pconrad** [comment]
If you were making a branch for this story, the branch name might be `5pm-c-avgClassSizeByDept`
