### ISSUE TITLE
Statistics Drop Down Menu Navbar Item

### ISSUE THREAD

**Issue by jvoucsb** [ucsb-cs156-f20/proj-ucsb-courses-search#55]
As a user I can click on a navbar item named Statistics to receive a drop down menu so that I can select which statistics page to go to.

# Acceptance Criteria

- [x] There is a navbar item called Statistics
- [x] There is a drop down menu with four items
    - [x] Number of full courses
    - [x] Department Course Occupancy,
    - [x] Department Course Occupancy by class level,
    - [x] Average class size by department

# Implementation Todos

Front end:

- [x] Add a Statistics to NavBar
- [x] Add drop down menu component

Testing:

- [x] Front end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
Nice job @jvoucsb 

Here's the code you need to get to 100% test coverage for this.   Put this into: `javascript/src/test/pages/Statistics/Statistics.test.js`

Not all front end testing will be this easy, but in this case, it is :-)

```javascript`
import React from "react";
import { render } from "@testing-library/react";
import Statistics from "main/pages/Statistics/Statistics";

describe("Statistics page tests", () => {
  test("renders without crashing", () => {
    render(<Statistics />);
  });
});

```

**Comment by pconrad** [comment]
Branch is `jv-addStatisticsNavbarMenu`
