### ISSUE TITLE
Convert JSON format into a table of course Id, title, instructor

### ISSUE THREAD

**Issue by andrewberry391** [ucsb-cs156-f20/proj-ucsb-courses-search#56]
# User Story

As a user I can see the course titles, Id's and instructors when searching so that I know the basic information of each course in a better format than JSON.

# Acceptance Criteria

- [x] Every course title, Id, and the instructor is displayed in table format.
- [x] Courses that don't have a specified instructor still show up correctly.

# Implementation Todos

Front end:

- [x] Extract the necessary information from the JSON and display it in a table format.

Back end:

- No changes needed

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

**Comment by maodougansidui** [comment]
Already done the table formatting and display information properly, need to work on the testing

**Comment by maodougansidui** [comment]
Nothing to add testing case here, mvn mutation coverage 100% and npm react testing 100%.
