### ISSUE TITLE
Display course sections

### ISSUE THREAD

**Issue by andrewberry391** [ucsb-cs156-f20/proj-ucsb-courses-search#61]
# User Story

As a user, I can see all the sections for a course so that I know which courses/sections I am taking.

# Acceptance Criteria

- [x] All sections of courses are displayed.
- [x] Lecture sections versus discussion sections can be visually distinguished.

# Implementation Todos

Front end:

- [x] Reformat the json so that it is a list of sections rather than a list of courses.
- [x] Figure out how to distinguish between lecture and discussion sections. (e.g. is the section number a multiple of 100)
- [x] Research react bootstrap table next to figure out the best way to visually distinguish lecture versus discussion.

Back end:

- Nothing in the back end for this one yet.

Testing:

- [x] Front end tests pass and there is adequate coverage

**Comment by maodougansidui** [comment]
Hi, Angela and Andrew, nice work done! You finish the majority of work 👍
